apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vikunja-files-pvc
  namespace: vikunja
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vikunja
  namespace: vikunja
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vikunja
  template:
    metadata:
      labels:
        app: vikunja
    spec:
      securityContext:
        fsGroup: 0
      containers:
      - name: vikunja
        image: vikunja/vikunja:latest
        securityContext:
          runAsUser: 0
        env:
        - name: VIKUNJA_DATABASE_TYPE
          value: postgres
        - name: VIKUNJA_DATABASE_HOST
          value: postgres
        - name: VIKUNJA_DATABASE_USER
          value: vikunja
        - name: VIKUNJA_DATABASE_PASSWORD
          value: changeme123
        - name: VIKUNJA_DATABASE_DATABASE
          value: vikunja
        - name: VIKUNJA_SERVICE_PUBLICURL
          value: https://vikunja.massivehog.win
        ports:
        - containerPort: 3456
        volumeMounts:
        - name: files
          mountPath: /app/vikunja/files
      volumes:
      - name: files
        persistentVolumeClaim:
          claimName: vikunja-files-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: vikunja
  namespace: vikunja
spec:
  selector:
    app: vikunja
  ports:
  - port: 3456
    targetPort: 3456
