apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:PresidentOfTheBigTime/demiurge-gitops.git
    targetRevision: HEAD
    path: apps/vaultwarden
  destination:
    server: https://kubernetes.default.svc
    namespace: vaultwarden
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vikunja
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:PresidentOfTheBigTime/demiurge-gitops.git
    targetRevision: HEAD
    path: apps/vikunja
  destination:
    server: https://kubernetes.default.svc
    namespace: vikunja
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:PresidentOfTheBigTime/demiurge-gitops.git
    targetRevision: HEAD
    path: apps/ollama
  destination:
    server: https://kubernetes.default.svc
    namespace: ollama
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: perplexica
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:PresidentOfTheBigTime/demiurge-gitops.git
    targetRevision: HEAD
    path: apps/perplexica
  destination:
    server: https://kubernetes.default.svc
    namespace: perplexica
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: syncthing
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:PresidentOfTheBigTime/demiurge-gitops.git
    targetRevision: HEAD
    path: apps/syncthing
  destination:
    server: https://kubernetes.default.svc
    namespace: syncthing
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: squid
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:PresidentOfTheBigTime/demiurge-gitops.git
    targetRevision: HEAD
    path: apps/squid
  destination:
    server: https://kubernetes.default.svc
    namespace: squid
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:PresidentOfTheBigTime/demiurge-gitops.git
    targetRevision: HEAD
    path: apps/cloudflared
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflared
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
