apiVersion: v1
kind: ConfigMap
metadata:
  name: perplexica-config
  namespace: perplexica
data:
  config.toml: |
    [GENERAL]
    PORT = 3000
    SIMILARITY_MEASURE = "cosine"

    [API_KEYS]
    OPENAI = ""
    GROQ = ""
    ANTHROPIC = ""

    [API_ENDPOINTS]
    SEARXNG = "http://searxng:8080"
    OLLAMA = "http://ollama.ollama.svc.cluster.local:11434"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: perplexica-data
  namespace: perplexica
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: perplexica
  namespace: perplexica
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: perplexica
  template:
    metadata:
      labels:
        app: perplexica
    spec:
      containers:
      - name: perplexica
        image: itzcrazykns1337/perplexica:latest
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: data
          mountPath: /home/perplexica/data
        - name: config
          mountPath: /home/perplexica/config.toml
          subPath: config.toml
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: perplexica-data
      - name: config
        configMap:
          name: perplexica-config
---
apiVersion: v1
kind: Service
metadata:
  name: perplexica
  namespace: perplexica
spec:
  selector:
    app: perplexica
  ports:
  - port: 3000
    targetPort: 3000
