apiVersion: apps/v1
kind: Deployment
metadata:
  name: searxng
  namespace: perplexica
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searxng
  template:
    metadata:
      labels:
        app: searxng
    spec:
      containers:
      - name: searxng
        image: searxng/searxng:latest
        ports:
        - containerPort: 8080
        env:
        - name: SEARXNG_BASE_URL
          value: "http://searxng:8080"
        volumeMounts:
        - name: config
          mountPath: /etc/searxng/settings.yml
          subPath: settings.yml
      volumes:
      - name: config
        configMap:
          name: searxng-config
---
apiVersion: v1
kind: Service
metadata:
  name: searxng
  namespace: perplexica
spec:
  selector:
    app: searxng
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: searxng-config
  namespace: perplexica
data:
  settings.yml: |
    use_default_settings: true
    server:
      secret_key: "changeme123randomstring"
      limiter: false
      image_proxy: true
    search:
      safe_search: 0
      formats:
        - html
        - json
